[package]
name = "bcsort"
version = "0.1.0"
edition = "2021"
authors = ["Hédi Ben Chiboub"]
description = "A fast, statistical, in-place ternary distribution sort."

[dependencies]
rayon = "1"
rand = "0.8"
radsort = "0.1.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1